計算アプリ課題
kmhm212/calc_app pull request #1
Opened 2021-11-09 04:23 UTC by kmhm212

2021-11-09 06:39 UTC, kazu-taka requested changes
@kmhm212 
コメントしたので確認お願いします:bow:

2021-11-09 06:39 UTC, kazu-taka commented on resources/views/result.blade.php
> +
@kmhm212 
Laravelの場合は、ビュー側で計算等はせずにコントローラーで計算するようにして下さい✨
計算した結果をビューに渡して表示するように修正お願いします😊

2021-11-09 06:39 UTC, kazu-taka commented on routes/web.php
> +use PhpParser\Node\Stmt\Break_;
@kmhm212 
この記述ななくても動いたと思いますが、何かで使うために追加しました！？😊

2021-11-10 04:22 UTC, kmhm212 commented on routes/web.php
> +use PhpParser\Node\Stmt\Break_;
コントローラー追加時に自動で記述されていました。削除します。

2021-11-10 07:39 UTC, kzri4 commented
@kmhm212 

確認しました！
ここの部分の削除ができていないので、削除の上マージで問題ございません😊
https://github.com/kmhm212/calc_app/pull/1#discussion_r745324834

1点だけ補足になりますが、`view`を作成する際、今回は`resources/views`の中に直接`result.blade.php`を作成して頂いてますが、resources/views`の中に`calc`フォルダーを作成して、その中に`result.blade.php`を作成する方がベターです😊

2021-11-11 04:17 UTC, merged